---
apiVersion: v1
kind: Namespace
metadata:
  name: organizer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: organizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: postgres-data
        hostPath:
          path: /organizer/db/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: organizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lukasblaha/organizer-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder
  namespace: organizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder
  template:
    metadata:
      labels:
        app: reminder
    spec:
      containers:
      - name: reminder
        image: lukasblaha/organizer-reminder:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DSN
          value: "postgres://postgres:postgres@postgres:5432/organizer?sslmode=disable"
