version: '3'

services:
  backend:
    build:
      context: ../backend
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  reminder:
    build:
      context: ../reminder
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
